Starknet fetcher improvements and tests
astraly-labs/pragma-sdk pull request #67
Opened 2024-01-27 19:22 UTC by JordyRo1

- [X ] Handle STRK/USD
- [X] Adding on chain tests and tests for STRK/USD

2024-01-27 19:23 UTC, JordyRo1 commented
Small issue with the async testing of the starknet amm: 
ClientConnectionError('Connection refused: POST https://starknet-testnet.public.blastapi.io/rpc/v0_6')

2024-01-30 17:44 UTC, EvolveArt requested changes
left few comments

2024-01-30 17:44 UTC, EvolveArt commented on pragma/core/assets.py
> +    {"type": "SPOT", "pair": ("STRK", "USD"), "decimals": 18},
decimals should be 8

2024-01-30 17:44 UTC, EvolveArt commented on pragma/publisher/fetchers/starknetamm.py
> +            logger.error("Pair not available for the Starknet fetcher")
return `PublisherFetchError` no?

2024-01-30 17:44 UTC, EvolveArt commented on pragma/publisher/fetchers/starknetamm.py
> +            ekubo_price = (
move common logic to an external function

2024-01-30 17:44 UTC, EvolveArt commented on pragma/publisher/fetchers/starknetamm.py
> +                asset["pair"] == ("ETH", "STRK") or asset["pair"] == ("STRK", "USD")
create a list of supported assets

2024-01-30 17:44 UTC, EvolveArt commented on pragma/tests/fetchers_test.py
> +        # for element in expected_result:
not needed ? if so remove comment

2024-01-30 17:44 UTC, EvolveArt commented on pragma/publisher/fetchers/starknetamm.py
> +            defillama_fetcher = DefillamaFetcher(self.ETH_USD, self.publisher)
I would prefer if we query it on-chain using `client.get_data` rather than adding a dependency on another fetcher, wdyt ?

2024-01-31 13:24 UTC, EvolveArt approved these changes

2024-01-31 13:26 UTC, merged