Index coop fetcher
astraly-labs/pragma-sdk pull request #97
Opened 2024-04-10 10:29 UTC by JordyRo1

2024-04-10 10:32 UTC, JordyRo1 commented
The index coop fetcher works individually, but the associated test fails due to an aiohttp.client_exceptions.ClientConnectionError. This error is also reported by other fetchers. I will fix them in another pr.

2024-04-10 13:21 UTC, EvolveArt requested changes

2024-04-10 13:21 UTC, EvolveArt commented on pragma/tests/fetcher_configs.py
> +                "DPI",
DPI/USD ?

2024-04-10 13:21 UTC, EvolveArt commented on pragma/tests/fetchers_test.py
> +        ]
Explain in the comment why this change and create a function filter_assets for example

2024-04-15 09:49 UTC, EvolveArt approved these changes

2024-04-15 09:50 UTC, merged